version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: f1_postgres
    environment:
      POSTGRES_DB: f1db
      POSTGRES_USER: f1
      POSTGRES_PASSWORD: f1
    ports:
      - "5433:5432"